# Generated by Django 3.2.2 on 2021-05-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'URL_FILE',
                'verbose_name_plural': 'URL_FILES',
            },
        ),
    ]
