# Generated by Django 3.2.2 on 2021-05-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_file',
            name='json_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
