# Generated by Django 3.2.2 on 2021-05-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_url_file_json_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_file',
            name='json_file',
            field=models.FileField(upload_to='media/json_file/'),
        ),
    ]
