# Generated by Django 3.2.2 on 2021-05-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_url_file_json_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='media/received_csv')),
            ],
            options={
                'verbose_name': 'URL_FILE',
                'verbose_name_plural': 'URL_FILES',
            },
        ),
    ]
