# Generated by Django 3.2.2 on 2021-05-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_receivedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_file',
            name='csv',
            field=models.FileField(default=1, upload_to='media/received_csv'),
            preserve_default=False,
        ),
    ]
