# Generated by Django 3.2.2 on 2021-05-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_url_file_csv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivedfile',
            old_name='csv_file',
            new_name='url_file',
        ),
        migrations.AlterField(
            model_name='url_file',
            name='csv',
            field=models.FileField(upload_to='received_csv/'),
        ),
    ]
